# Auto-generated by Maxima
import numpy as np
from numpy import sqrt, exp, cos, sin

def get_wn_zeta(m, c, k):
    wn = sqrt(k/m)
    zeta = c/(2*sqrt(m*k))
    return float(wn), float(zeta)

def analytic_solution(t, m, c, k, x0, v0):
    wn = sqrt(k/m)
    zeta = c/(2*sqrt(m*k))
    if zeta < 1.0:
        wd = wn*sqrt(1 - zeta**2)
        A = x0
        B = (v0 + zeta*wn*x0)/wd
        return exp(-zeta*wn*t)*(A*cos(wd*t) + B*sin(wd*t))
    elif abs(zeta - 1.0) < 1e-8:
        A = x0
        B = v0 + wn*x0
        return (A + B*t)*exp(-wn*t)
    else:
        r1 = -wn*zeta + wn*sqrt(zeta**2 - 1)
        r2 = -wn*zeta - wn*sqrt(zeta**2 - 1)
        C2 = (v0 - r1*x0)/(r2 - r1)
        C1 = x0 - C2
        return C1*exp(r1*t) + C2*exp(r2*t)
